# Generated by Django 5.0.6 on 2025-02-02 17:12

import apps.atividade_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtividadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_ativo', models.BooleanField(default=True)),
                ('ram_dataInicial', models.DateTimeField(default=apps.atividade_app.models.hora_atual, editable=False)),
                ('ram_dataFinal', models.DateTimeField(blank=True, null=True)),
                ('ram_duracao', models.DurationField(blank=True, null=True)),
                ('ram_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.atividade')),
                ('ram_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.cliente')),
                ('ram_colaborador', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ram_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.servico')),
            ],
        ),
    ]
