# Generated by Django 5.1.3 on 2025-02-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroatividademodel',
            old_name='ram_atividade',
            new_name='RAM_atividade',
        ),
        migrations.RenameField(
            model_name='registroatividademodel',
            old_name='ram_ativo',
            new_name='RAM_ativo',
        ),
        migrations.RenameField(
            model_name='registroatividademodel',
            old_name='ram_cliente',
            new_name='RAM_cliente',
        ),
        migrations.RenameField(
            model_name='registroatividademodel',
            old_name='ram_colaborador',
            new_name='RAM_colaborador',
        ),
        migrations.RenameField(
            model_name='registroatividademodel',
            old_name='ram_dataFinal',
            new_name='RAM_dataFinal',
        ),
        migrations.RenameField(
            model_name='registroatividademodel',
            old_name='ram_dataInicial',
            new_name='RAM_dataInicial',
        ),
        migrations.RenameField(
            model_name='registroatividademodel',
            old_name='ram_duracao',
            new_name='RAM_duracao',
        ),
        migrations.RenameField(
            model_name='registroatividademodel',
            old_name='ram_servico',
            new_name='RAM_servico',
        ),
    ]
