# Generated by Django 5.1.3 on 2025-02-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade_app', '0002_rename_ram_atividade_registroatividademodel_ram_atividade_and_more'),
        ('base_app', '0002_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatividademodel',
            name='RAM_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.periodo'),
        ),
    ]
